[project]
name = "prettylogging"
version = "0.1.0"
description = ""
authors = [
    {name = "AlessandroLovo",email = "alessandro.lovo@mitigasolutions.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "prettylogging", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
